author: Max Qiu
theme: jekyll-theme-cayman
description: Come and read about my blogs about git,Github,and websites. Read my journal to see my feelings and thoughts. 
google_analytics: UA-229561715-2
social-network-links:
    email: maxqqqq@hotmail.com
    twitter: maxqiu15
    github: qqiumax
    reddit: Maxqzc