title: Max's Website
author: Max Qiu
theme: jekyll-theme-cayman
social-network-links:
  email: "maxqzc@protonmail.com"
  github: qqiumax
  twitter: maxqiu15
  youtube: c/Max_Qiu
reddit: Maxqzc
keywords: Git,Github,Cryptocurrency,Website,Journal,Feelings
google_analytics: "UA-229561715-5"
gtag: "G-TKGR7R82EL"
gtm: "GTM-MTFWPGZ"
description: Look at my journals for my feelings and thoughts. Blogs to learn Git, Github, and Website! Build ur own site!
