author: Max Qiu
theme: jekyll-theme-cayman
keywords: Git,Github,Cryptocurrency,Website,Journal,Feelings, Github, Page, Google Analytics. News.
description: "Look at my journals for my feelings and thoughts. Blogs to learn Git, Github, and Website! Build ur own site! Here you can learn about me, to build a website with markdown, write your own blog, plot Github Pages!"
