author: Max Qiu
theme: jekyll-theme-cayman
google_analytics: UA-229561715-5
description: Look at my journals for my feelings and thoughts. Blogs to learn Git, Github, and Website! Build ur own site!
gtag: G-TKGR7R82EL
gtm: GTM-MTFWPGZ