author: Max Qiu
theme: jekyll-theme-cayman
keywords: Git,Github,Cryptocurrency,Website,Journal,Feelings
google_analytics: "UA-229561715-5"
description: Look at my journals for my feelings and thoughts. Blogs to learn Git, Github, and Website! Build ur own site!
